/**
 * Minimal, dependency-free Markdown → HTML renderer for AURA chat messages.
 *
 * Security model:
 *   1. ALL raw HTML in the model output is escaped first, so nothing from the
 *      LLM can inject markup.
 *   2. Only tags generated by this function are added afterwards.
 *   3. Angular's [innerHTML] binding sanitizes the result again as a final
 *      layer of defense.
 *
 * Supported syntax (sufficient for AURA's response style):
 *   fenced code blocks, inline code, headings (#..###), bold, italic,
 *   bullet/ordered lists, links (http/https only), paragraphs/line breaks.
 */

const CODE_BLOCK_PLACEHOLDER_PREFIX = '\u0000AURACB';
const INLINE_CODE_PLACEHOLDER_PREFIX = '\u0000AURAIC';

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/** Render a markdown string to trusted-ish HTML (still sanitized by Angular). */
export function renderMarkdown(raw: string | null | undefined): string {
  if (!raw) return '';
  let text = escapeHtml(raw);

  // ── Extract fenced code blocks before other transforms ──
  const codeBlocks: string[] = [];
  text = text.replace(/```([\s\S]*?)```/g, (_match, code: string) => {
    codeBlocks.push(`<pre><code>${code.replace(/^\n+|\n+$/g, '')}</code></pre>`);
    return `${CODE_BLOCK_PLACEHOLDER_PREFIX}${codeBlocks.length - 1}\u0000`;
  });

  // ── Extract inline code so emphasis rules don't mangle it ──
  const inlineCodes: string[] = [];
  text = text.replace(/`([^`\n]+)`/g, (_match, code: string) => {
    inlineCodes.push(`<code>${code.trim()}</code>`);
    return `${INLINE_CODE_PLACEHOLDER_PREFIX}${inlineCodes.length - 1}\u0000`;
  });

  // ── Links (http/https only) ──
  text = text.replace(
    /\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g,
    '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>'
  );

  // ── Headings ──
  text = text.replace(/^###\s+(.+)$/gm, '<h4>$1</h4>');
  text = text.replace(/^##\s+(.+)$/gm, '<h3>$1</h3>');
  text = text.replace(/^#\s+(.+)$/gm, '<h2>$1</h2>');

  // ── Bold then italic ──
  text = text.replace(/\*\*([^*\n]+)\*\*/g, '<strong>$1</strong>');
  text = text.replace(/(^|[\s(])\*([^*\n]+)\*(?=[\s).,;:!?]|$)/g, '$1<em>$2</em>');

  // ── Lists + paragraphs, line by line ──
  const lines = text.split('\n');
  const html: string[] = [];
  let listBuffer: string[] = [];
  let listType: 'ul' | 'ol' | null = null;

  const flushList = () => {
    if (listType && listBuffer.length > 0) {
      html.push(`<${listType}>${listBuffer.join('')}</${listType}>`);
    }
    listBuffer = [];
    listType = null;
  };

  for (const line of lines) {
    const trimmed = line.trim();

    const bulletMatch = /^[-*]\s+(.*)$/.exec(trimmed);
    if (bulletMatch) {
      if (listType && listType !== 'ul') flushList();
      listType = 'ul';
      listBuffer.push(`<li>${bulletMatch[1]}</li>`);
      continue;
    }

    const orderedMatch = /^\d+[.)]\s+(.*)$/.exec(trimmed);
    if (orderedMatch) {
      if (listType && listType !== 'ol') flushList();
      listType = 'ol';
      listBuffer.push(`<li>${orderedMatch[1]}</li>`);
      continue;
    }

    flushList();

    if (trimmed === '') {
      continue; // blank lines act as paragraph separators
    }

    const isBlock =
      trimmed.startsWith(CODE_BLOCK_PLACEHOLDER_PREFIX) ||
      trimmed.startsWith('<h2>') ||
      trimmed.startsWith('<h3>') ||
      trimmed.startsWith('<h4>') ||
      trimmed.startsWith('<pre>');

    html.push(isBlock ? trimmed : `<p>${trimmed}</p>`);
  }
  flushList();

  let result = html.join('\n');

  // ── Restore code fragments ──
  result = result.replace(
    new RegExp(`${INLINE_CODE_PLACEHOLDER_PREFIX}(\\d+)\u0000`, 'g'),
    (_m, index: string) => inlineCodes[Number(index)] ?? ''
  );
  result = result.replace(
    new RegExp(`${CODE_BLOCK_PLACEHOLDER_PREFIX}(\\d+)\u0000`, 'g'),
    (_m, index: string) => codeBlocks[Number(index)] ?? ''
  );

  return result.trim();
}
